default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: FinMan_Api_development

test:
  <<: *default
  database: FinMan_Api_test

production:
  <<: *default
  database: FinMan_Api_production
  username: FinMan_Api
  password: <%= ENV["FINMAN_API_DATABASE_PASSWORD"] %>
