name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
  RUBY_VERSION: 3.1.2
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: FinMan_Api_test
  POSTGRES_HOST: localhost
  DATABASE_URL: postgres://postgres:postgres@localhost/FinMan_Api_test

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Analyze code
      run: bundle exec rubocop

  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Build
      env:
        DATABASE_URL: ${{ env.DATABASE_URL }}
        RAILS_ENV: test
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rails db:create
        bundle exec rails db:migrate
    - name: Test
      env:
        DATABASE_URL: ${{ env.DATABASE_URL }}
        RAILS_ENV: test
      run: |
        bundle exec rspec -f doc